name: ci-cd-pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      ECR_REPO: ${{ secrets.ECR_REPO }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      EKS_CLUSTER_NAME: ${{ secrets.EKS_CLUSTER_NAME }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Terraform Init
        run: terraform -chdir=terraform init

      - name: Terraform Plan
        run: terraform -chdir=terraform plan

      - name: Terraform Apply
        run: terraform -chdir=terraform apply -auto-approve

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push backend image
        run: |
          docker build -t $ECR_REPO/backend:latest ./backend
          docker push $ECR_REPO/backend:latest

      - name: Build, tag, and push frontend image
        run: |
          docker build -t $ECR_REPO/frontend:latest ./frontend
          docker push $ECR_REPO/frontend:latest

      - name: Update Helm values with new image tags
        run: |
          sed -i "s|image:.*backend:.*|image: $ECR_REPO/backend:latest|" helm/backend/values.yaml
          sed -i "s|image:.*frontend:.*|image: $ECR_REPO/frontend:latest|" helm/frontend/values.yaml

      - name: Commit Helm updates
        run: |
          git config --global user.email "ci@github.com"
          git config --global user.name "GitHub Actions"
          git add helm/*/values.yaml
          git commit -m "Update Helm image tags"
          git push origin main
      
      - name: Install Prometheus & Grafana
        run: |
          helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
          helm repo add grafana https://grafana.github.io/helm-charts
          helm repo update
          helm upgrade --install kube-prometheus prometheus-community/kube-prometheus-stack \
            --namespace monitoring --create-namespace
